# Generated by Django 5.0.2 on 2024-02-19 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_state', models.CharField(default='waiting', max_length=20)),
                ('current_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_game_player', to='words_game.player')),
                ('players', models.ManyToManyField(to='words_game.player')),
            ],
        ),
    ]
